user www-data;
worker_processes auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;
include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections 768;
	# multi_accept on;
}

http {

	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	types_hash_max_size 2048;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# SSL Settings
	##

	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_prefer_server_ciphers on;

	##
	# Logging Settings
	##

	access_log /var/log/nginx/access.log;

	##
	# Gzip Settings
	##

	gzip on;

	##
	# Virtual Host Configs
	##

	server {
		listen 443 ssl;
		ssl_certificate /etc/nginx/ssl/cert.crt;
		ssl_certificate_key /etc/nginx/ssl/certkey.key;

		#root tells nginx where are the files for the website (entrypoint). Index is the first file shown
		root /var/www/wordpress;			#This matches where wordpress is installed
		server_name daxferna.42.fr;
		index index.php index.html;

		# try file or directory, if it doesn't exist:
		# pass the request to index.php with the query arguments
		# This lets WordPress handle its own routing
		location / {
			try_files $uri $uri/ /index.php?$args;
		}
	
		# This "~ \.php$" means apply this to all requests that end with .php
		location ~ \.php$ {
			include snippets/fastcgi-php.conf;
			fastcgi_pass wordpress:9000;		#Send PHP requests through port 9000 (Wordpress port)
		}
	}

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
}
